# A string used to distinguish different Supabase projects on the same host.
project_id = "etziwqjmkwuqntcmqadz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15
shadow_port = 54320

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"

[auth.email.template.invite]
subject = "You have been invited"
content_path = "supabase/templates/invite.html"

[auth.email.template.confirm]
subject = "Confirm your email"
content_path = "supabase/templates/confirm.html"

[auth.email.template.confirm_change]
subject = "Confirm email change"
content_path = "supabase/templates/confirm-change.html"

[auth.email.template.reset]
subject = "Reset your password"
content_path = "supabase/templates/reset.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "supabase/templates/magic-link.html"

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"

[auth.sms.twilio]
enabled = false  # Enable and configure in Supabase dashboard

[auth.external.google]
enabled = false  # We will handle OAuth in Edge Functions
client_id = ""
secret = "hash:"
url = ""
redirect_uri = "https://etziwqjmkwuqntcmqadz.supabase.co/functions/v1/gmail-callback"

[analytics]
enabled = false
port = 54328

[functions]
[functions.gmail-auth]
verify_jwt = true
[functions.gmail-callback]
verify_jwt = false
