# A string used to distinguish different Supabase projects on the same host.
project_id = "etziwqjmkwuqntcmqadz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15
shadow_port = 54320

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"

[auth.email.template.invite]
subject = "You have been invited"
content = "\n<h2>You have been invited</h2>\n\n<p>You have been invited to create a user on {{ .SiteURL }}. Follow this link to accept the invite:</p>\n<p><a href=\"{{ .ConfirmationURL }}\">Accept the invite</a></p>\n"

[auth.email.template.confirm]
subject = "Confirm your email"
content = "\n<h2>Confirm your email</h2>\n\n<p>Follow this link to confirm your email:</p>\n<p><a href=\"{{ .ConfirmationURL }}\">Confirm your email</a></p>\n"

[auth.email.template.confirm_change]
subject = "Confirm email change"
content = "\n<h2>Confirm email change</h2>\n\n<p>Follow this link to confirm your new email:</p>\n<p><a href=\"{{ .ConfirmationURL }}\">Confirm email change</a></p>\n"

[auth.email.template.reset]
subject = "Reset your password"
content = "\n<h2>Reset your password</h2>\n\n<p>Follow this link to reset the password for your user:</p>\n<p><a href=\"{{ .ConfirmationURL }}\">Reset password</a></p>\n"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content = "\n<h2>Magic Link</h2>\n\n<p>Follow this link to login:</p>\n<p><a href=\"{{ .ConfirmationURL }}\">Log In</a></p>\n"

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"

# Add Twilio as SMS provider
[auth.sms.twilio]
enabled = true
account_sid = ""  # Will be set via environment variable AUTH_SMS_TWILIO_ACCOUNT_SID
auth_token = ""   # Will be set via environment variable AUTH_SMS_TWILIO_AUTH_TOKEN
message_service_id = ""  # Will be set via environment variable AUTH_SMS_TWILIO_MESSAGE_SERVICE_ID

[auth.external.google]
enabled = false  # We'll handle OAuth in Edge Functions
client_id = ""
secret = "hash:"
url = ""
redirect_uri = "https://etziwqjmkwuqntcmqadz.supabase.co/functions/v1/gmail-callback"

[analytics]
enabled = false
port = 54328

[functions]
[functions.gmail-auth]
verify_jwt = true
[functions.gmail-callback]
verify_jwt = false