-- Update agents table
ALTER TABLE agents
  ADD COLUMN IF NOT EXISTS edge_function TEXT NOT NULL DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS config JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}';