CREATE TABLE prospects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    company TEXT,
    linkedin_url TEXT,
    email TEXT,
    score FLOAT,
    status TEXT NOT NULL DEFAULT 'new',
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes
CREATE INDEX idx_prospects_company ON prospects(company);
CREATE INDEX idx_prospects_status ON prospects(status);
CREATE INDEX idx_prospects_score ON prospects(score);

-- Add trigger for updated_at
CREATE TRIGGER update_prospects_updated_at
    BEFORE UPDATE ON prospects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE prospects IS 'Stores identified sales prospects';
COMMENT ON COLUMN prospects.status IS 'Status of the prospect (new, contacted, qualified, etc)';
COMMENT ON COLUMN prospects.score IS 'Match score based on criteria (0-1)';
COMMENT ON COLUMN prospects.metadata IS 'Additional enriched data about the prospect'; 